print (2 + 3)
print(2)
print(3)
print(2 + 3)
print('Hello world')
print("Hello\t\tworld")
print("1. Hello\n2. World")
print("Hello\n\n\n\n\nGoodbye world")
print("Hello \"world\"")
print("Hello \'world\'")
